### PR TITLE
add `cancelSubscription`

### PR DESCRIPTION
**Pull request by adrian-gierakowski**
only supported by google engine

apologies for no tests as no time to spare atm

### CODE REVIEW

**Comment by KLVTZ** [comment]
I think this may be out-of-scope of this package. But I could be wrong. This offers a solution to cancel the subscription through google but not the other payment services. I think we would need a comprehensive solution for each to support this. 

In addition, I think we should consider the following scenario with Android: users can cancel their subscription outside the app. That is, they can cancel their subscription without doing so within the app. When this happens, its good to have the receipt validation service check the receipt status. 

Is there any problems this pull requests solves for you and/or your team? Can you provide more context?

Thanks!

**Comment by adrian-gierakowski** [comment]
> This offers a solution to cancel the subscription through google but not the other payment services

There is no such option for Apple subscriptions. Not sure about the other providers

> When this happens, its good to have the receipt validation service check the receipt status.

The way to handle it is to:
1. Store the receipt when subscription is initiated
2. Verify the receipt shortly after the subscription period is due to end. At this point you will know if user cancelled or if the subscription has been renewed ( if so, repeat the same check at the end of next sub period )

Both AppStore and Playstore subscriptions run until the end of current period when cancelled. I don't think there is a way of getting notified about a cacelation other then re-validating the receipt.

> Is there any problems this pull requests solves for you and/or your team? 

It is used to enable the user to easily cancel a sub from within the app. And for support people  to be able to cancel a subscription when users request it ( when for some reason they are unable or unwilling to do so themselves).

Since we were already using your module for validation it was a no brainer to add this method to it. Otherwise I'd have to duplicate all the authentication code you've got there.

**Comment by ronkorving** [comment]
I'm okay with this logic being added. I think what @adrian-gierakowski says makes sense, in that you don't really want to reinvent the authentication mechanism. I think it fits within the scope of IAP, so I'm okay with it 👍 
Some documentation in the readme would be most welcome though :)

**Comment by adrian-gierakowski** [comment]
@ronkorving done

**Comment by adrian-gierakowski** [comment]
@ronkorving @KLVTZ ping!

**Comment by KLVTZ** [comment]
I think our plan is to merge #40 which might cause more conflicts for your PR.

Once all that is resolved, I wouldn't mind testing this out.

Some other thoughts...

>  I don't think there is a way of getting notified about a cacelation other then re-validating the receipt.

Google does offer a solution but they tie it to their pub/sub service:

https://developer.android.com/google/play/billing/realtime_developer_notifications

> It is used to enable the user to easily cancel a sub from within the app. And for support people to be able to cancel a subscription when users request it ( when for some reason they are unable or unwilling to do so themselves).

Right! We do this already for customers in which we have their billing information on hand. Being able to cancel their third-party store subscriptions would be very helpful.

**Comment by adrian-gierakowski** [comment]
@KLVTZ just ping me one that PR is merged and I'll resolve any conflicts that might arise

**Comment by KLVTZ** [comment]
@adrian-gierakowski #40 is merged. Feel free to resolve any conflicts.

**Comment by justinpage** [comment]
@adrian-gierakowski any updates?

**Comment by adrian-gierakowski** [comment]
@justinpage will submit a PR today

**Comment by adrian-gierakowski** [comment]
closing in favour of #55

**Pull request closed without merging**
