### PR TITLE
Created verifyPayment alternative function to return Promise

### LINKED ISSUE #68: Create verifyPayment function that returns a Promise, instead of using callbacks
Since the function verifyPayment only works with callback, when I try to check the payment with the Apple store, when it responds and I can't return the result from the controller to the router, in order to send a response with it to the client.

**Router code:**
```
router.get('/subscriptionCheck', verifyToken, async function(req, res) {
    try {
        const subscription = await subscriptionController.getSubscription(req.userId);

        if (!subscription) return res.status(404).send('Failed to get subscription.');

        const response = await subscriptionController.checkSubscription(subscription.receipt);

        if(response.active){
            return res.status(200).json(response.data);
        } else {
            return res.status(400).json(response.data);
        }
    } catch (error) {
        return res.status(500).json({error: error.message});
    }
 });
```

**Controller code:**
```
 async function checkSubscriptionIOS(receipt, productId) {
    const payment = {
        receipt: receipt,
        productId: productId,
        packageName: 'bundleId',
        secret: 'secret',
    };

    return iap.verifyPayment('apple', payment, function(error, response) {
        if(error) {
            console.log("verify Apple subscriptions error:\n", error);

            return {active: false, data: error};
        } else {
            if (response.receipt.in_app.expires_date_ms < new Date().getTime()) {
                return {active: false, data: response};
            }

            return {active: true, data: response};
        }
    });
 }
```

### PR DESCRIPTION
**Pull request by faboyds**
Created an alternative method for verifyPayment that uses promises instead of callbacks.

Should fix #68

### CODE REVIEW

**Comment by ronkorving** [comment]
This removes the callback-style API from the library. In other words, while your new function works, the old one is gone (overwritten).

I would love Promise support, so I think you're on the right track here, but we need a solid solution that we can apply to all APIs, while still supporting callback-style. I think it's possible. Please reconsider a solution.

**Comment by faboyds** [comment]
Ok, I understand and I agree with you. I will take a deeper look into this when I have more time, and I'll try to deliver a more complete solution.

**Comment by superandrew213** [comment]
@faboyds have a look how I did it here: https://github.com/superandrew213/react-native-in-app-utils/blob/listen-for-purchase-event/index.js

You end up with a single method that you can call like this if you want to use callbacks:

```js
method(arg1, arg2, (error, res) => {})
```

or like this if you want to use Promises:

```js
method(arg1, arg2).then(res => {}).catch(error => {})
```

**Comment by justinpage** [comment]
@faboyds An alternative way you could handle this issue is through bluebird promisfy all:

http://bluebirdjs.com/docs/api/promise.promisifyall.html

Simply wrap the existing package:

```
const iap: any = Bluebird.promisifyAll(require("iap"));
```

And then you can do something like:

```
        // Verify payment from iap service
        let responseFromApple = await iap.verifyPaymentAsync(
            "apple", subscriptionWithSharedSecret
        )
        .catch(e => {
            logger.error(
                "Receipt.validateApplePurchase: failed to validate apple " +
                "receipt",
                { message: e.message, subscription }
            );

            return Err("ValidationError", e.message);
        });

        if (isError(responseFromApple)) {
            return responseFromApple;
        }
```

**Comment by faboyds** [comment]
> @faboyds have a look how I did it here: https://github.com/superandrew213/react-native-in-app-utils/blob/listen-for-purchase-event/index.js
> 
> You end up with a single method that you can call like this if you want to use callbacks:
> 
> ```js
> method(arg1, arg2, (error, res) => {})
> ```
> 
> or like this if you want to use Promises:
> 
> ```js
> method(arg1, arg2).then(res => {}).catch(error => {})
> ```

I followed this implementation. Please check if the code is now meeting the requirements. 
And thank you for your suggestions! 😄

**Comment by artur-ma** [comment]
Can it be merged?

**Comment by ronkorving** [comment]
Done, cheers 👍

**Comment by SeanDunford** [comment]
Could we get this released on npm?

Relevant issue here https://github.com/Wizcorp/node-iap/issues/81

**Pull request merged**
