### PR TITLE
fix Wizcorp/node-iap#10, apple receipt format

### PR DESCRIPTION
**Pull request by samuelregev**

### CODE REVIEW

**Comment by ronkorving** [comment]
I don't have this problem, so in the least your change would break my own use case it seems. Some more information wouldn't be bad.

**Comment by samuelregev** [comment]
if you try to verify manuelly by posting to apple - you'll get this response.
what is the response you're getting

https://gist.github.com/samuelregev/1d3cef03d3bf986b70291418a3ca0247

**Comment by ronkorving** [comment]
I get, for example (although I did have to censor this):

```json
{
	"receipt": {
		"original_purchase_date_pst": "2016-09-13 04:39:28 America/Los_Angeles",
		"purchase_date_ms": "1473766768744",
		"unique_identifier": "SOMEHASH",
		"original_transaction_id": "SOMENUMBER",
		"bvrs": "0",
		"transaction_id": "SOMENUMBER",
		"quantity": "1",
		"unique_vendor_identifier": "SOME-UUID",
		"item_id": "SOMENUMBER",
		"product_id": "SOMESTRING",
		"purchase_date": "2016-09-13 11:39:28 Etc/GMT",
		"original_purchase_date": "2016-09-13 11:39:28 Etc/GMT",
		"purchase_date_pst": "2016-09-13 04:39:28 America/Los_Angeles",
		"bid": "SOMEBUNDLEID",
		"original_purchase_date_ms": "1473766768744"
	},
	"transactionId": "SOMENUMBER",
	"productId": "SOMEPRODUCTID",
	"platform": "apple"
}
```

**Comment by samuelregev** [comment]
it looks like an old response
did this response came from posting your receipt-data directly to apple now ?

cause mine did.

**Comment by ronkorving** [comment]
Mine came from a game that was released only a few weeks ago. This is nothing legacy in my case as far as I can tell.

**Comment by KLVTZ** [comment]
@ronkorving this can be closed in favor of #24

**Pull request closed without merging**
