### PR TITLE
add subscription renewal information on apple receipt

### PR DESCRIPTION
**Pull request by MarcEtienneDery**

### CODE REVIEW

**Comment by ronkorving** [comment]
Thanks for your contribution! This LGTM. Wouldn't mind someone else signing off on it too before I merge it though.

cc @KLVTZ

**Comment by KLVTZ** [comment]
@MarcEtienneDery thanks for including this!

@ronkorving I would like to get #40 in first. Afterwards, we can adopt the same pattern in having a fallback when `pending_renewal_info` is not found. I have plenty of active receipts that don't have this field so a discrete fallback would explain why the value may be null or some other default value.

**Comment by sarunw** [comment]
@KLVTZ #40 is already merged, do you have plan to merge this?

**Comment by KLVTZ** [comment]
@sarunw Can you review how #40 has fallbacks when a field is not available? In other words, we should check to see if this field exists before including it. I have plenty of active receipts that don't have this field so a discrete fallback would explain why the value may be null or some other default value.

**Comment by sarunw** [comment]
@KLVTZ If this field is not present it will be undefined just like `latestExpiredReceiptInfo` what behavior do you want if it not present? Remove the key or set it to null.

**Comment by sarunw** [comment]
I made new PR here https://github.com/Wizcorp/node-iap/pull/48

**Comment by KLVTZ** [comment]
I think we should merge #48 instead of #46.

#48 PR would satisfy #46 in addition to including some safe fallbacks.

**Comment by ronkorving** [comment]
#48 is merged. Let's close this.

**Pull request closed without merging**
